home/urls.py
from django.urls import path, include
from django.contrib.auth import logout

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.login, name='login'),
    path('map/', views.map, name='map'),
    path('updateprofile/', views.updateProf, name='updateProfile'),
    path('submit_location/', views.submit_location, name='submit_location'),
    path('create_user/', views.create_user, name="create_user"),
    path('users_list/', views.users_list, name="users_list"),
    path('home/', views.home, name="home")
]

quick_tutor/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('home.urls', namespace='home')),
    path('', include('home.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('logout/', views.logout_view,
         {'next_page': settings.LOGOUT_REDIRECT_URL}, name="logout")
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import datetime
from django.conf import settings


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    online = models.BooleanField(default=False)
    latitude = models.DecimalField(
        max_digits=10, decimal_places=7, default=0.0000000)
    longitude = models.DecimalField(
        max_digits=10, decimal_places=7, default=0.0000000)
    status = models.CharField(max_length=15, default='Hanging Out')
    subject = models.CharField(max_length=150, default='School Work')
    geodata = models.CharField(max_length=50)

    def __str__(self):
        return F"Username: {self.user.email} is Online: {self.online}"

    @receiver(post_save, sender=User)
    def create_or_update_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
        else:
            instance.userprofile.save()

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm
from .models import*


class UpdateUser(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username',)


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['status', 'subject']

home/views.py
import requests
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.context_processors import auth
from django.urls import reverse
from .models import UserProfile
from .forms import *
import os
from dotenv import load_dotenv


def map(request):
    user = auth(request)['user']
    if user.is_authenticated:


             # sets the user to be online when they are on the map
            user.userprofile.online = True
            user.userprofile.save()

            users_list = User.objects.all()

            non_admin_users_list = []

            # removes the admin from the list of online users  displayed
            for user in users_list:
                if not user.is_staff:
                    non_admin_users_list.append(user)

            # makes sure people are online in the context users list
            online_users = [
                person for person in non_admin_users_list if person.userprofile.online == True]

            return render(request, 'home/map.html', {'users_list': online_users})

    else:
        return HttpResponseRedirect(reverse('home:login'))


def create_user(request):
    user = auth(request)['user']
    if not hasattr(user, 'userprofile'):
        profile = UserProfile()
        profile.user = user
        profile.save()

    return HttpResponseRedirect(reverse('home:map'))


def submit_location(request):
    user = auth(request)['user']
    load_dotenv()
    GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

    if user.is_authenticated:
        if request.method == 'GET':
            return
        elif request.method == 'POST':
            d = request.POST.dict()
            user.userprofile.latitude = d['latitude']
            user.userprofile.longitude = d['longitude']
            user.userprofile.save()

            response = requests.get(
                F'https://maps.googleapis.com/maps/api/geocode/json?latlng={user.userprofile.latitude},{user.userprofile.longitude}&key={GOOGLE_API_KEY}')
            geodata = "".join(response.json(
            )['results'][0]['formatted_address'].split(',')[0:3])

            user.userprofile.geodata = geodata
            user.userprofile.save()
            return HttpResponse('')
    else:
        return render(request, 'home/login.html', {})


def login(request):
    user = auth(request)['user']
    if user.is_authenticated:
        return HttpResponseRedirect(reverse('home:map'))
    else:
        return HttpResponseRedirect(reverse('home:home'))


def home(request):
    return render(request, 'home/login.html', {})


def users_list(request):
    user = auth(request)['user']
    if user.is_authenticated:
        users_list = User.objects.all()

        non_admin_users_list = []

        # removes the admin from the list of online users  displayed
        for user in users_list:
            if not user.is_staff:
                non_admin_users_list.append(user)

        # makes sure people are online in the context users list
        online_users = [
            person for person in non_admin_users_list if person.userprofile.online == True]

        return render(request, 'home/users_list.html', {'users_list': online_users})
    else:
        return render(request, 'home/login.html', {})


def updateProf(request):

    user = auth(request)['user']
    if user.is_authenticated:
        if request.method == 'POST':
            user_form = UpdateUser(request.POST, instance=request.user)
            profile_form = UserProfileForm(
                request.POST, instance=request.user.userprofile)
            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save(commit=False)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()
                return HttpResponseRedirect(reverse('home:users_list'))

        else:
            profile_form = UserProfileForm(instance=request.user.userprofile)
            user_form = UpdateUser(instance=request.user)
            args = {'user_form': user_form, 'profile_form': profile_form}
            return render(request, 'home/updateprofile.html', args)

    else:
        return render(request, 'home/login.html', {})

quick_tutor/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render
from django.contrib.auth import logout
from django.contrib.auth.context_processors import auth
from home.models import UserProfile


def logout_view(request, next_page):
    user = auth(request)['user']

    # sets a user to "offline" once they have logged out
    user.userprofile.online = False
    user.userprofile.save()

    logout(request)
    return HttpResponseRedirect(redirect_to=next_page)

home/templates/home/login.html
{% extends "base.html" %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Quick Tutor - home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>

<body>

  <div class="jumbotron contrainer">
    <div class="row">
      <div class="col-sm-6">
        <img src="https://i.ibb.co/c8s8rYB/Logo.png" alt="Logo" style="margin-bottom:0.5rem;" height="60" border="0">
        <h3 style="margin-bottom:2rem;"><b>Quick Tutor</b></h3>
        <h4>Get help fast! Connect with a tutor, peer, or student nearby quickly!</h4>
      </div>
      <div class="col-sm-6">
        <img src="https://cdn.zeemaps.com/images/base/create-free-map.png" alt="" width="225" height="225">
      </div>
    </div>
  </div>

  <div class="container">
    <h2>Getting started: </h2>
    <div class="row">
      <div class="col-sm-4">
            <h2>Login</h2>
            <p>Log into Quick Tutor using a valid UVA google account!</p>
      </div>
      <div class="col-sm-4">
            <h2>Map</h2>
            <p>Use the map tab to see, in real-time, where other active users are located and what they are working on!
        </p>
      </div>
      <div class="col-sm-4">
            <h2>User List</h2>
            <p>Search through other students online right now and contact them to set up tutoring sessions!</p>
      </div>
    </div>
  </div>

</body>

</html>


{% endblock content %}

home/templates/home/logout.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron">
  <h1>My fake blog!</h1>
  {% endblock content %}
</div>

home/templates/home/map.html
{% extends "base.html" %}
{% block content %}

<head>
  <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v1.8.0/mapbox-gl.css' rel='stylesheet' />
</head>

<body>
  <div id='map' style='height: 300px;'></div>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoidG9tYXRvcGllIiwiYSI6ImNrNndvemRvdzBmMDUzbW1ndDU2bmdxaTAifQ.qbLK7dK0nlmBY7FByF9Shw';
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-78.5045525, 38.0355725],
      zoom: 14,


    });
    let geoTracker = new mapboxgl.GeolocateControl({
      positionOptions: {
        enableHighAccuracy: true
      },
      trackUserLocation: true
    });

    map.addControl(
      geoTracker
    );

    setTimeout(function () {
      geoTracker.trigger(); },1000);

  </script>
</body>
<div class="jumbotron">

  <script>
    var options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };
    function success(pos) {
      $.post({
        url: "/submit_location/",

        data: { latitude: pos.coords.latitude, longitude: pos.coords.longitude },

        headers: {
          'X-CSRFToken': '{{ csrf_token }}'
        },
      });
    }
    function error(err) {
      console.warn(`ERROR(${err.code}): ${err.message}`);
    }
    navigator.geolocation.getCurrentPosition(success, error, options);

    var geojson = {}
   {% for person in users_list %}
      // add markers to map
        geojson = {
        type: 'FeatureCollection',
        features: [{
          type: 'Feature',
          geometry: {
            type: 'Point',
            coordinates: [{{person.userprofile.longitude}}, {{person.userprofile.latitude}}]
          },
          properties: {
            title: '{{person.first_name}} {{person.last_name}}',
            description: 'Status: {{person.userprofile.status}}',
            subject: 'Subject: {{person.userprofile.subject}}',
            email: '{{person.email}}',
           }
           }]
           }

      geojson.features.forEach(function(marker) {
        console.log("here")

        // create a HTML element for each feature
        var el = document.createElement('div');
        el.className = 'marker';

        // make a marker for each feature and add to the map
        new mapboxgl.Marker(el)
          .setLngLat(marker.geometry.coordinates)
.setPopup(new mapboxgl.Popup({ offset: 25 }) // add popups
    .setHTML('<h3>' + marker.properties.title + '</h3><p>' + marker.properties.description + '</p><p>' + marker.properties.subject + '</p><p>' + marker.properties.email + '</p>'))
          .addTo(map);
      });

    {% endfor %}
  </script>

  {% if user.is_authenticated %}
 
  <div class="container p-3 mb-2 bg-light text-dark">
    <p class="h5">
    Logged in as {{ user.first_name }} {{ user.last_name }} {{ user.username }}
    {{user.date_joined }} {{ user.email }}
    </p>
  </div>

  {% endif %}
</div>

{% endblock content %}

home/templates/home/updateprofile.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron">
    <h2>Please edit the info you wish to change and hit the submit button</h2>
</div>

<div class="container-fluid">
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <button type="submit" class="btn btn-primary">Submit Change</button>
    </form>
</div>

{% endblock content %}

home/templates/home/users_list.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron">
    <table class="table table-hover table-info">
        <thead>
            <tr>
                <th scope=" col">Email Address</th>
                <th scope="col">First Name</th>
                <th scope="col">Status</th>
                <th scope="col">Subject Focus</th>
                <th scope="col">Location </th>
            </tr>
        </thead>
        <tbody>
            {% for person in users_list %}
            <tr>
                <th scope="row">

                    {{ person.email | urlize}}

                </th>
                <td>{{person.first_name}}</td>
                <td>{{person.userprofile.status}}</td>
                <td>{{person.userprofile.subject}}</td>
                <td>{{person.userprofile.geodata}}</td>
            </tr>
            {% endfor %}
        </tbody>
</div>


<div class="container-fluid">


</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
  <!--bootstrap css-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}" />
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

  <div> </div>
</head>

<body class="text-center">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <img src="https://i.ibb.co/c8s8rYB/Logo.png" alt="Logo" style="margin-right:10px;" height="42" border="0">
    <a class="navbar-brand" href="{% url 'home:home' %}">
      <b>Quick Tutor</b>
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
      aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="d-flex justify-content-around navbar-nav mr-auto">
        <li class="nav-item active" style="margin-left:1rem; margin-right:1rem;">
          <a class="nav-link" href="{% url 'home:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active" style="margin-right:1rem;">
          <a class="nav-link" href="{% url 'home:users_list' %}">User List <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'home:map' %}">Map <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <div class="update-profile">
          <a class="btn btn-info" href="{% url 'home:updateProfile' %}">Update Profile <span
              class="sr-only">(current)</span></a>
        </div>
        {% if user.is_authenticated %}
        <a class="btn btn-info" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="btn btn-info" href="{% url 'social:begin' 'google-oauth2' %}">
          Login
        </a>
        {% endif %}

      </form>
    </div>
  </nav>
  <main role="main" class="flex-shrink-0 main-container">
    <div class="container">


      {% block content %}{% endblock content %}
    </div>
  </main>

  {% block javascript %}{% endblock %}
</body>

</html>